language: go
go:
  - 1.11.x
  - 1.10.x
  - 1.9.x
  - master
script: 
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic
  - go test -run=none -bench=^Benchmark -benchmem
notifications:
  email: false
